import type { Appointment, AppointmentStatus, AvailabilityException, AvailabilityExceptionType, AvailabilityRule, BusinessProfile, Customer, CustomerSummary, OperatingHoursDay, Professional, ProfessionalService, ScheduleAppointmentInput, Service, ServiceCategory, ServiceSummary } from "../dtos";

export interface AdministrationGateway {
  readonly appointments: { day(businessId: string, date: string): Promise<Appointment[]>; week(businessId: string, weekStartsOn: string): Promise<Appointment[]>; month(businessId: string, year: number, month: number): Promise<Appointment[]>; create(businessId: string, input: ScheduleAppointmentInput): Promise<unknown>; updateStatus(businessId: string, appointmentId: string, status: AppointmentStatus, reason?: string): Promise<unknown>; reschedule(businessId: string, appointmentId: string, startsAtUtc: string): Promise<unknown>; };
  readonly overview: { profile(businessId: string): Promise<BusinessProfile>; operatingHours(businessId: string): Promise<OperatingHoursDay[]>; customers(businessId: string, includeInactive?: boolean): Promise<CustomerSummary[]>; services(businessId: string, includeInactive?: boolean): Promise<ServiceSummary[]>; updateProfile(businessId: string, input: Pick<BusinessProfile, "name" | "legalName" | "documentNumber" | "slug" | "timeZone">): Promise<BusinessProfile>; replaceOperatingHours(businessId: string, days: OperatingHoursDay[]): Promise<unknown>; };
  readonly customers: { get(businessId: string, id: string): Promise<Customer>; create(businessId: string, input: Pick<Customer, "fullName" | "phone" | "email">): Promise<Customer>; update(businessId: string, id: string, input: Pick<Customer, "fullName" | "phone" | "email" | "isActive">): Promise<Customer>; remove(businessId: string, id: string): Promise<unknown>; };
  readonly categories: { list(businessId: string, includeInactive?: boolean): Promise<ServiceCategory[]>; get(businessId: string, id: string): Promise<ServiceCategory>; create(businessId: string, input: Pick<ServiceCategory, "name" | "description">): Promise<ServiceCategory>; update(businessId: string, id: string, input: Pick<ServiceCategory, "name" | "description" | "isActive">): Promise<ServiceCategory>; remove(businessId: string, id: string): Promise<unknown>; };
  readonly services: { get(businessId: string, id: string): Promise<Service>; create(businessId: string, input: Omit<Service, "id" | "businessId" | "isActive">): Promise<Service>; update(businessId: string, id: string, input: Omit<Service, "id" | "businessId">): Promise<Service>; remove(businessId: string, id: string): Promise<unknown>; };
  readonly professionals: { list(businessId: string, includeInactive?: boolean): Promise<Professional[]>; get(businessId: string, id: string): Promise<Professional>; create(businessId: string, input: Pick<Professional, "displayName" | "businessMembershipId">): Promise<Professional>; update(businessId: string, id: string, input: Pick<Professional, "displayName" | "businessMembershipId" | "isActive">): Promise<Professional>; remove(businessId: string, id: string): Promise<unknown>; services(businessId: string, professionalId: string): Promise<ProfessionalService[]>; upsertService(businessId: string, professionalId: string, serviceId: string, input: { durationInMinutes: number | null; price: number | null; isActive: boolean }): Promise<ProfessionalService>; removeService(businessId: string, professionalId: string, serviceId: string): Promise<unknown>; };
  readonly availability: { rules(businessId: string, professionalId?: string, includeInactive?: boolean): Promise<AvailabilityRule[]>; rule(businessId: string, id: string): Promise<AvailabilityRule>; createRule(businessId: string, input: Pick<AvailabilityRule, "professionalId" | "dayOfWeek" | "startTime" | "endTime">): Promise<AvailabilityRule>; updateRule(businessId: string, id: string, input: Pick<AvailabilityRule, "dayOfWeek" | "startTime" | "endTime" | "isActive">): Promise<AvailabilityRule>; removeRule(businessId: string, id: string): Promise<unknown>; exceptions(businessId: string, professionalId?: string): Promise<AvailabilityException[]>; exception(businessId: string, id: string): Promise<AvailabilityException>; createException(businessId: string, input: { professionalId: string; date: string; type: AvailabilityExceptionType; startTime: string | null; endTime: string | null; reason: string | null }): Promise<AvailabilityException>; updateException(businessId: string, id: string, input: Omit<AvailabilityException, "id" | "professionalId">): Promise<AvailabilityException>; removeException(businessId: string, id: string): Promise<unknown>; };
}
