import { type FormEvent, useState } from "react";

import { useAuthStore } from "@/auth/authStore";
import { useApiData } from "@/hook/useApiData";
import { AdminDrawer, AdminEmptyRow, AdminTabs, PageFeedback, StatusPill } from "@/shared/AdminUi";
import FormField from "@/shared/FormField";
import { availabilityApi, professionalsApi } from "@/service/api";
import type { AvailabilityException, AvailabilityExceptionType, AvailabilityRule, Professional } from "@/service/api";

type Tab = "rules" | "exceptions";
const DAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const DAY_LABEL: Record<string, string> = { Sunday: "Domingo", Monday: "Segunda-feira", Tuesday: "Terca-feira", Wednesday: "Quarta-feira", Thursday: "Quinta-feira", Friday: "Sexta-feira", Saturday: "Sabado" };
const EMPTY_RULE = { id: "", professionalId: "", dayOfWeek: "Monday", startTime: "09:00", endTime: "18:00", isActive: true };
const EMPTY_EXCEPTION: { id: string; professionalId: string; date: string; type: AvailabilityExceptionType; startTime: string; endTime: string; reason: string } = { id: "", professionalId: "", date: "", type: "Unavailable", startTime: "", endTime: "", reason: "" };

const AvailabilityPage = () => {
  const businessId = useAuthStore((state) => state.activeBusiness?.businessId ?? "");
  const permissions = useAuthStore((state) => state.permissions);
  const [tab, setTab] = useState<Tab>("rules");
  const [professionalFilter, setProfessionalFilter] = useState("");
  const professionals = useApiData<Professional[]>(() => professionalsApi.list(businessId), businessId, []);
  const rules = useApiData<AvailabilityRule[]>(() => availabilityApi.rules(businessId, professionalFilter || undefined), `${businessId}:${professionalFilter}`, []);
  const exceptions = useApiData<AvailabilityException[]>(() => availabilityApi.exceptions(businessId, professionalFilter || undefined), `${businessId}:${professionalFilter}`, []);
  const [ruleForm, setRuleForm] = useState(EMPTY_RULE);
  const [exceptionForm, setExceptionForm] = useState(EMPTY_EXCEPTION);
  const [drawer, setDrawer] = useState<Tab | null>(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const activeProfessionals = professionals.data.filter((item) => item.isActive);
  const professionalName = (id: string) => professionals.data.find((item) => item.id === id)?.displayName ?? "Profissional";

  const editRule = async (summary: AvailabilityRule) => { setDrawer("rules"); setBusy(true); try { const item = await availabilityApi.rule(businessId, summary.id); setRuleForm({ ...item }); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Nao foi possivel carregar a regra."); } finally { setBusy(false); } };
  const editException = async (summary: AvailabilityException) => { setDrawer("exceptions"); setBusy(true); try { const item = await availabilityApi.exception(businessId, summary.id); setExceptionForm({ id: item.id, professionalId: item.professionalId, date: item.date, type: item.type, startTime: item.startTime?.slice(0, 5) ?? "", endTime: item.endTime?.slice(0, 5) ?? "", reason: item.reason ?? "" }); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Nao foi possivel carregar a excecao."); } finally { setBusy(false); } };

  const saveRule = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setMessage(""); try { const input = { professionalId: ruleForm.professionalId, dayOfWeek: ruleForm.dayOfWeek, startTime: ruleForm.startTime, endTime: ruleForm.endTime, isActive: ruleForm.isActive }; if (ruleForm.id) await availabilityApi.updateRule(businessId, ruleForm.id, input); else await availabilityApi.createRule(businessId, input); setDrawer(null); await rules.reload(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Nao foi possivel salvar a regra."); } finally { setBusy(false); } };
  const saveException = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setMessage(""); try { const input = { date: exceptionForm.date, type: exceptionForm.type, startTime: exceptionForm.startTime || null, endTime: exceptionForm.endTime || null, reason: exceptionForm.reason.trim() || null }; if (exceptionForm.id) await availabilityApi.updateException(businessId, exceptionForm.id, input); else await availabilityApi.createException(businessId, { ...input, professionalId: exceptionForm.professionalId }); setDrawer(null); await exceptions.reload(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Nao foi possivel salvar a excecao."); } finally { setBusy(false); } };
  const removeRule = async (item: AvailabilityRule) => { if (!window.confirm("Excluir esta regra?")) return; try { await availabilityApi.removeRule(businessId, item.id); await rules.reload(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Nao foi possivel excluir."); } };
  const removeException = async (item: AvailabilityException) => { if (!window.confirm("Excluir esta excecao?")) return; try { await availabilityApi.removeException(businessId, item.id); await exceptions.reload(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Nao foi possivel excluir."); } };

  return <div className="tirr__admin__page"><section className="tirr__admin__panel"><div className="tirr__admin__panel-header"><div><p className="tirr__admin__overline">Organizacao da jornada</p><h2>Disponibilidade</h2></div><div className="tirr__admin__toolbar"><select className="form-select" value={professionalFilter} onChange={(event) => setProfessionalFilter(event.target.value)} disabled={!professionals.data.length}><option value="">Todos os profissionais</option>{professionals.data.map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select>{tab === "rules" && permissions.includes("availability_rules.post") && <button className="btn btn-primary" disabled={!activeProfessionals.length} onClick={() => { setRuleForm({ ...EMPTY_RULE, professionalId: professionalFilter || activeProfessionals[0]?.id || "" }); setDrawer("rules"); }}><i className="bi bi-plus-lg" /> Nova regra</button>}{tab === "exceptions" && permissions.includes("availability_exceptions.post") && <button className="btn btn-primary" disabled={!activeProfessionals.length} onClick={() => { setExceptionForm({ ...EMPTY_EXCEPTION, professionalId: professionalFilter || activeProfessionals[0]?.id || "" }); setDrawer("exceptions"); }}><i className="bi bi-plus-lg" /> Nova excecao</button>}</div></div>
    <AdminTabs value={tab} onChange={(value) => setTab(value as Tab)} items={[{ value: "rules", label: "Regras semanais", icon: "bi-arrow-repeat" }, { value: "exceptions", label: "Excecoes", icon: "bi-calendar-x" }]} />{message && <div className="tirr__inline-alert">{message}</div>}
    {tab === "rules" && <><PageFeedback loading={rules.loading || professionals.loading} error={rules.error || professionals.error} onRetry={() => void rules.reload()} /><div className="tirr__admin__data-list">{rules.data.map((item) => <article className="tirr__admin__data-row" key={item.id}><span className="tirr__admin__client-avatar"><i className="bi bi-clock" /></span><div className="tirr__admin__data-main"><h3>{DAY_LABEL[item.dayOfWeek] ?? item.dayOfWeek}</h3><p>{professionalName(item.professionalId)}</p></div><div><small>Horario</small><span>{item.startTime.slice(0, 5)} - {item.endTime.slice(0, 5)}</span></div><StatusPill active={item.isActive} /><div className="tirr__row-actions">{permissions.includes("availability_rules.put") && <button className="tirr__admin__icon-button" onClick={() => void editRule(item)} aria-label="Editar regra"><i className="bi bi-pencil" /></button>}{permissions.includes("availability_rules.delete") && <button className="tirr__admin__icon-button is-danger" onClick={() => void removeRule(item)} aria-label="Excluir regra"><i className="bi bi-trash" /></button>}</div></article>)}{!rules.loading && !rules.data.length && <AdminEmptyRow>Nenhuma regra cadastrada.</AdminEmptyRow>}</div></>}
    {tab === "exceptions" && <><PageFeedback loading={exceptions.loading || professionals.loading} error={exceptions.error || professionals.error} onRetry={() => void exceptions.reload()} /><div className="tirr__admin__data-list">{exceptions.data.map((item) => <article className="tirr__admin__data-row" key={item.id}><span className="tirr__admin__client-avatar"><i className={`bi ${item.type === "Unavailable" ? "bi-calendar-x" : "bi-calendar-plus"}`} /></span><div className="tirr__admin__data-main"><h3>{new Date(`${item.date}T12:00:00`).toLocaleDateString("pt-BR", { dateStyle: "long" })}</h3><p>{professionalName(item.professionalId)} · {item.reason || (item.type === "Unavailable" ? "Indisponivel" : "Horario extra")}</p></div><div><small>Periodo</small><span>{item.startTime && item.endTime ? `${item.startTime.slice(0, 5)} - ${item.endTime.slice(0, 5)}` : "Dia inteiro"}</span></div><StatusPill tone={item.type === "Unavailable" ? "danger" : "info"} label={item.type === "Unavailable" ? "Indisponivel" : "Extra"} /><div className="tirr__row-actions">{permissions.includes("availability_exceptions.put") && <button className="tirr__admin__icon-button" onClick={() => void editException(item)} aria-label="Editar excecao"><i className="bi bi-pencil" /></button>}{permissions.includes("availability_exceptions.delete") && <button className="tirr__admin__icon-button is-danger" onClick={() => void removeException(item)} aria-label="Excluir excecao"><i className="bi bi-trash" /></button>}</div></article>)}{!exceptions.loading && !exceptions.data.length && <AdminEmptyRow>Nenhuma excecao cadastrada.</AdminEmptyRow>}</div></>}
    </section>
    <AdminDrawer open={drawer === "rules"} title={ruleForm.id ? "Editar regra" : "Nova regra semanal"} onClose={() => setDrawer(null)} onSubmit={saveRule} busy={busy}><div className="tirr__drawer-fields"><label className="tirr__form-field"><span>Profissional</span><select className="form-select" value={ruleForm.professionalId} onChange={(event) => setRuleForm({ ...ruleForm, professionalId: event.target.value })} required>{professionals.data.filter((item) => item.isActive).map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label><label className="tirr__form-field"><span>Dia da semana</span><select className="form-select" value={ruleForm.dayOfWeek} onChange={(event) => setRuleForm({ ...ruleForm, dayOfWeek: event.target.value })}>{DAYS.map((day) => <option key={day} value={day}>{DAY_LABEL[day]}</option>)}</select></label><div className="tirr__field-grid"><FormField id="rule-start" label="Inicio" type="time" value={ruleForm.startTime.slice(0, 5)} onChange={(event) => setRuleForm({ ...ruleForm, startTime: event.target.value })} required /><FormField id="rule-end" label="Fim" type="time" value={ruleForm.endTime.slice(0, 5)} onChange={(event) => setRuleForm({ ...ruleForm, endTime: event.target.value })} required /></div>{ruleForm.id && <label className="tirr__toggle-row"><input type="checkbox" checked={ruleForm.isActive} onChange={(event) => setRuleForm({ ...ruleForm, isActive: event.target.checked })} /><span><strong>Regra ativa</strong><small>Considerada no calculo de horarios.</small></span></label>}</div></AdminDrawer>
    <AdminDrawer open={drawer === "exceptions"} title={exceptionForm.id ? "Editar excecao" : "Nova excecao"} onClose={() => setDrawer(null)} onSubmit={saveException} busy={busy}><div className="tirr__drawer-fields"><label className="tirr__form-field"><span>Profissional</span><select className="form-select" value={exceptionForm.professionalId} onChange={(event) => setExceptionForm({ ...exceptionForm, professionalId: event.target.value })} disabled={Boolean(exceptionForm.id)}>{professionals.data.filter((item) => item.isActive).map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label><FormField id="exception-date" label="Data" type="date" value={exceptionForm.date} onChange={(event) => setExceptionForm({ ...exceptionForm, date: event.target.value })} required /><label className="tirr__form-field"><span>Tipo</span><select className="form-select" value={exceptionForm.type} onChange={(event) => setExceptionForm({ ...exceptionForm, type: event.target.value as "Unavailable" })}><option value="Unavailable">Indisponibilidade</option><option value="ExtraAvailability">Disponibilidade extra</option></select></label><div className="tirr__field-grid"><FormField id="exception-start" label="Inicio (opcional)" type="time" value={exceptionForm.startTime} onChange={(event) => setExceptionForm({ ...exceptionForm, startTime: event.target.value })} /><FormField id="exception-end" label="Fim (opcional)" type="time" value={exceptionForm.endTime} onChange={(event) => setExceptionForm({ ...exceptionForm, endTime: event.target.value })} /></div><FormField id="exception-reason" label="Motivo" value={exceptionForm.reason} onChange={(event) => setExceptionForm({ ...exceptionForm, reason: event.target.value })} /></div></AdminDrawer>
  </div>;
};

export default AvailabilityPage;
