import { type FormEvent, useState } from "react";

import { useAuthStore } from "@/auth/authStore";
import { useApiData } from "@/hook/useApiData";
import { AdminDrawer, AdminEmptyRow, AdminTabs, PageFeedback, StatusPill } from "@/shared/AdminUi";
import FormField from "@/shared/FormField";
import { identityApi, overviewApi, professionalsApi } from "@/service/api";
import type { BusinessMemberListItem, IdentityUser, Professional, ProfessionalService, ServiceSummary } from "@/service/api";
import { formatToBRL } from "@/utils/formatToBRL";

const ROLES = ["Owner", "Administrator", "Receptionist", "Professional"];
const EMPTY_PROFESSIONAL = { id: "", displayName: "", businessMembershipId: "", isActive: true };

const TeamPageV2 = () => {
  const businessId = useAuthStore((state) => state.activeBusiness?.businessId ?? "");
  const permissions = useAuthStore((state) => state.permissions);
  const [tab, setTab] = useState("professionals");
  const professionals = useApiData<Professional[]>(() => professionalsApi.list(businessId), businessId, []);
  const members = useApiData<BusinessMemberListItem[]>(() => permissions.includes("users.get") ? identityApi.members(businessId) : Promise.resolve([]), `${businessId}:${permissions.join("|")}`, []);
  const catalog = useApiData<ServiceSummary[]>(() => overviewApi.services(businessId), businessId, []);
  const [professionalForm, setProfessionalForm] = useState(EMPTY_PROFESSIONAL);
  const [professionalDrawer, setProfessionalDrawer] = useState(false);
  const [serviceDrawer, setServiceDrawer] = useState<Professional | null>(null);
  const [professionalServices, setProfessionalServices] = useState<ProfessionalService[]>([]);
  const [email, setEmail] = useState("");
  const [foundUser, setFoundUser] = useState<IdentityUser | null>(null);
  const [newUser, setNewUser] = useState({ fullName: "", password: "" });
  const [roles, setRoles] = useState<string[]>(["Professional"]);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");

  const editProfessional = async (summary: Professional) => { setProfessionalDrawer(true); setBusy(true); try { const item = await professionalsApi.get(businessId, summary.id); setProfessionalForm({ id: item.id, displayName: item.displayName, businessMembershipId: item.businessMembershipId ?? "", isActive: item.isActive }); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Nao foi possivel carregar."); } finally { setBusy(false); } };
  const saveProfessional = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setMessage(""); try { const input = { displayName: professionalForm.displayName.trim(), businessMembershipId: professionalForm.businessMembershipId || null, isActive: professionalForm.isActive }; if (professionalForm.id) await professionalsApi.update(businessId, professionalForm.id, input); else await professionalsApi.create(businessId, input); setProfessionalDrawer(false); await professionals.reload(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Nao foi possivel salvar."); } finally { setBusy(false); } };
  const removeProfessional = async (item: Professional) => { if (!window.confirm(`Excluir ${item.displayName}?`)) return; await professionalsApi.remove(businessId, item.id); await professionals.reload(); };
  const openServices = async (professional: Professional) => { setServiceDrawer(professional); setBusy(true); try { setProfessionalServices(await professionalsApi.services(businessId, professional.id)); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Nao foi possivel carregar os servicos."); } finally { setBusy(false); } };
  const toggleService = async (service: ServiceSummary, active: boolean) => { if (!serviceDrawer) return; setBusy(true); try { if (active) await professionalsApi.upsertService(businessId, serviceDrawer.id, service.serviceId, { durationInMinutes: null, price: null, isActive: true }); else await professionalsApi.removeService(businessId, serviceDrawer.id, service.serviceId); setProfessionalServices(await professionalsApi.services(businessId, serviceDrawer.id)); } finally { setBusy(false); } };

  const findUser = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setFoundUser(null); setMessage(""); try { setFoundUser(await identityApi.findByEmail(email.trim())); } catch { setMessage("Conta nao encontrada. Crie uma nova conta para continuar."); } finally { setBusy(false); } };
  const createUser = async () => { setBusy(true); try { const created = await identityApi.createUser(newUser.fullName.trim(), email.trim(), newUser.password); setFoundUser({ ...created, isActive: true }); setNewUser({ fullName: "", password: "" }); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Nao foi possivel criar."); } finally { setBusy(false); } };
  const addMember = async () => { if (!foundUser) return; setBusy(true); try { await identityApi.addMember(businessId, foundUser.id, roles); await members.reload(); setFoundUser(null); setEmail(""); setMessage("Acesso adicionado a empresa."); } catch (caught) { setMessage(caught instanceof Error ? caught.message : "Nao foi possivel adicionar."); } finally { setBusy(false); } };
  const replaceRoles = async (member: BusinessMemberListItem, nextRoles: string[]) => { await identityApi.replaceRoles(businessId, member.identityUserId, nextRoles); await members.reload(); };
  const toggleMember = async (member: BusinessMemberListItem) => { await identityApi.setMemberStatus(businessId, member.identityUserId, !member.isActive); await members.reload(); };

  return <div className="tirr__admin__page"><section className="tirr__admin__panel"><div className="tirr__admin__panel-header"><div><p className="tirr__admin__overline">Pessoas e acessos</p><h2>Equipe</h2></div>{tab === "professionals" && permissions.includes("professionals.post") && <button className="btn btn-primary" onClick={() => { setProfessionalForm(EMPTY_PROFESSIONAL); setProfessionalDrawer(true); }}><i className="bi bi-plus-lg" /> Novo profissional</button>}</div><AdminTabs value={tab} onChange={setTab} items={[{ value: "professionals", label: "Profissionais", icon: "bi-person-badge" }, { value: "access", label: "Acessos", icon: "bi-shield-lock" }]} />{message && <div className="tirr__inline-alert">{message}</div>}
    {tab === "professionals" && <><PageFeedback loading={professionals.loading} error={professionals.error} onRetry={() => void professionals.reload()} /><div className="tirr__admin__data-list">{professionals.data.map((item) => <article className="tirr__admin__data-row" key={item.id}><span className="tirr__admin__client-avatar"><i className="bi bi-person" /></span><div className="tirr__admin__data-main"><h3>{item.displayName}</h3><p>{item.businessMembershipId ? "Acesso vinculado" : "Sem acesso vinculado"}</p></div><StatusPill active={item.isActive} /><div className="tirr__row-actions"><button className="tirr__admin__icon-button" onClick={() => void openServices(item)} title="Servicos"><i className="bi bi-scissors" /></button>{permissions.includes("professionals.put") && <button className="tirr__admin__icon-button" onClick={() => void editProfessional(item)} title="Editar"><i className="bi bi-pencil" /></button>}{permissions.includes("professionals.delete") && <button className="tirr__admin__icon-button is-danger" onClick={() => void removeProfessional(item)} title="Excluir"><i className="bi bi-trash" /></button>}</div></article>)}{!professionals.loading && !professionals.data.length && <AdminEmptyRow>Nenhum profissional cadastrado.</AdminEmptyRow>}</div></>}
    {tab === "access" && <div className="tirr__access-layout"><section><h3>Adicionar acesso</h3><p>Localize ou crie uma conta e atribua papeis nesta empresa.</p><form className="tirr__inline-form" onSubmit={findUser}><FormField id="member-email" label="E-mail" type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /><button className="btn btn-outline-primary" disabled={busy}><i className="bi bi-search" /> Localizar</button></form>{!foundUser && email && <div className="tirr__create-user"><FormField id="member-name" label="Nome da nova conta" value={newUser.fullName} onChange={(event) => setNewUser({ ...newUser, fullName: event.target.value })} /><FormField id="member-password" label="Senha inicial" type="password" value={newUser.password} onChange={(event) => setNewUser({ ...newUser, password: event.target.value })} /><button className="btn btn-outline-secondary" type="button" onClick={() => void createUser()} disabled={!newUser.fullName || !newUser.password || busy}>Criar conta</button></div>}{foundUser && <div className="tirr__member-candidate"><span className="tirr__admin__client-avatar">{foundUser.fullName[0]}</span><div><strong>{foundUser.fullName}</strong><small>{foundUser.email}</small></div><StatusPill active={foundUser.isActive} /></div>}<fieldset className="tirr__role-picker"><legend>Papeis nesta empresa</legend>{ROLES.map((role) => <label key={role}><input type="checkbox" checked={roles.includes(role)} onChange={(event) => setRoles(event.target.checked ? [...roles, role] : roles.filter((item) => item !== role))} /><span>{role}</span></label>)}</fieldset><button className="btn btn-primary" disabled={!foundUser || !roles.length || busy} onClick={() => void addMember()}>Adicionar a empresa</button></section><section><h3>Membros da empresa</h3><p>Acessos e papeis sao exclusivos deste estabelecimento.</p><PageFeedback loading={members.loading} error={members.error} onRetry={() => void members.reload()} />{members.data.map((member) => <article key={member.identityUserId} className="tirr__member-row"><span className="tirr__admin__client-avatar">{member.fullName[0]}</span><div><strong>{member.fullName}</strong><small>{member.email} · {member.roles.join(" · ")}</small></div><select className="form-select" value={member.roles[0] ?? ""} onChange={(event) => void replaceRoles(member, [event.target.value])} disabled={!permissions.includes("users.put")}>{ROLES.map((role) => <option key={role}>{role}</option>)}</select>{permissions.includes("users.put") && <button className="btn btn-outline-secondary btn-sm" onClick={() => void toggleMember(member)}>{member.isActive ? "Inativar" : "Ativar"}</button>}</article>)}{!members.loading && !members.data.length && <AdminEmptyRow>Nenhum membro encontrado.</AdminEmptyRow>}</section></div>}
    </section><AdminDrawer open={professionalDrawer} title={professionalForm.id ? "Editar profissional" : "Novo profissional"} onClose={() => setProfessionalDrawer(false)} onSubmit={saveProfessional} busy={busy}><div className="tirr__drawer-fields"><FormField id="professional-name" label="Nome de exibicao" value={professionalForm.displayName} onChange={(event) => setProfessionalForm({ ...professionalForm, displayName: event.target.value })} required /><label className="tirr__form-field"><span>Conta de acesso (opcional)</span><select className="form-select" value={professionalForm.businessMembershipId} onChange={(event) => setProfessionalForm({ ...professionalForm, businessMembershipId: event.target.value })}><option value="">Sem conta vinculada</option>{members.data.filter((item) => item.isActive).map((item) => <option key={item.membershipId} value={item.membershipId}>{item.fullName}</option>)}</select></label>{professionalForm.id && <label className="tirr__toggle-row"><input type="checkbox" checked={professionalForm.isActive} onChange={(event) => setProfessionalForm({ ...professionalForm, isActive: event.target.checked })} /><span><strong>Profissional ativo</strong><small>Disponivel para configuracao.</small></span></label>}</div></AdminDrawer>
    <AdminDrawer open={Boolean(serviceDrawer)} title={`Servicos de ${serviceDrawer?.displayName ?? "profissional"}`} description="Defina quais atendimentos podem ser realizados." onClose={() => setServiceDrawer(null)} onSubmit={(event) => { event.preventDefault(); setServiceDrawer(null); }} busy={busy} submitLabel="Concluir"><PageFeedback loading={catalog.loading} error={catalog.error} onRetry={() => void catalog.reload()} />{!catalog.loading && !catalog.error && (catalog.data.length ? <div className="tirr__service-assignment-list">{catalog.data.map((service) => { const association = professionalServices.find((item) => item.serviceId === service.serviceId); return <label key={service.serviceId}><input type="checkbox" checked={Boolean(association?.isActive)} onChange={(event) => void toggleService(service, event.target.checked)} disabled={busy} /><span><strong>{service.name}</strong><small>{service.durationInMinutes} min · {formatToBRL(service.price)}</small></span></label>; })}</div> : <AdminEmptyRow icon="bi-scissors" description="Cadastre um servico no Catalogo antes de vincula-lo a um profissional.">Nenhum servico disponivel</AdminEmptyRow>)}</AdminDrawer>
  </div>;
};

export default TeamPageV2;
